### ISSUE TITLE
Layout shift issue upon pressing `delete` button

### ISSUE THREAD

**Issue by patel-devashish** [patel-devashish/vanilla-js-projects#1]

**Comment by Ayush21298** [comment]
``` css
.screen {
  width: 100%;
  padding: 20px;
  background: rgb(19, 43, 41);
  color: aliceblue;
  border-bottom: 2px solid #111;
  text-align: right;
  font-size: 40px;
}
```

Currently `font-size: 40px` and `padding: 20px`.

So if you set height as _font-size + padding-top + padding-bottom_, the height of the screen will remain constant.

Currently, _padding-top = padding-bottom = padding = 20px_

So, if you set `height: 80px`, the issue can be resolved :smiley:
